mysqlIp: 159.75.4.191
redisIp: 159.75.4.191

server:
  port: 5000
# 配置数据源
spring:
  # 定义swagger
  swagger:
    enabled: true # 生产环境中默认是不开启的

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysqlIp}:3306/forum_db2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: P!XcewfKwd85Xy0vXo+bbBFqerL3i&SWf~_0KL
    initial-size: 3
    min-idle: 3
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jdbc:
    template:
      query-timeout: 5

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.forum.entity
  configuration:
    # 驼峰映射关系
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

my-meta-data:
  # 时间格式
  time-type: yyyy-MM-dd HH:mm:ss

